### PR TITLE
add methods to programmatically slide view

### PR DESCRIPTION
**Pull request by turrea**
methods to programmatically slide view allow for one touch sidebar menu access (ie tapping a button in the body could slide view)

### CODE REVIEW

**Comment by bugwelle** [comment]
:+1: Need this desperately :D

**Comment by scottriggle** [comment]
Sorry can't seem to figure out how to use open and close.

**Comment by turrea** [comment]
You would call those methods on the slidingView object. I believe there is a global called slidingView created when you initialize the sliding view, so you would invoke methods as follows:

<code>window.slidingView.open();</code>

or

<code>slidingView.open();</code>

or if you store the sliding view in a local var
<code>
var slideMenu = new SlidingView('#id');
slideMenu.open();
slideMenu.close();
</code>

Hope that helps.

**Comment by scottriggle** [comment]
Worked great! Thanks!!!

**Comment by morandringer** [comment]
helped me too! thx!

**Pull request merged**
