### PR TITLE
add cross-browser CSS prefixes + cleaning + other cross-platform fixes

### PR DESCRIPTION
**Pull request by yocontra**

### CODE REVIEW

**Comment by bugwelle** [comment]
4 months ago... Well, maybe this can be merged now? :)
:+1: for cleaning the CSS in the examples :D

**Comment by yocontra** [comment]
AFAIK it looks like app-ui has been abandoned - I would suggest using rachet or sidetap

**Comment by bugwelle** [comment]
Well, I thought this, too... But thanks for the tip :) I'll have a look on Sidetap.

**Comment by triceam** [comment]
Nope, not abandoned... Just been traveling a lot, and project maintenance got pushed down priorities list.  I use a form of app ui almost every day.  Some pretty big updates coming to github later this month.

**Comment by bugwelle** [comment]
Well, that's a good message :D
:+1:

**Pull request merged**
